# Site settings
title: Fedspending.us
email:
description: > # this means to ignore newlines until "baseurl:"
  An exploration of publicly-available federal spending data.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://fedspending.us" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
